version: "3.5"

services:
  fuse-shared-mount:
    build:
      context: ./fuse-shared-mount
    container_name: ${PROJECT_NAME}-fuse-shared-mount
    image: ${PROJECT_NAME}/fuse-shared-mount:latest
    networks:
      - plexflix
    pid: host
    privileged: true
