#!/usr/bin/with-contenv bash

while [ ! -f "/config/config.json" ] || [ ! -f "/config/token.json" ]
do
  echo "Waiting for plexdrive configuration files ..."
  sleep 30
done

umask 022

mount_command="plexdrive mount -c /config/ --cache-file=/config/cache.bolt --uid=${PUID:-911} --gid=${PGID:-911} --root-node-id=${ROOT_FOLDER_ID:-root} -o allow_other,allow_non_empty_mount /data"

echo "Executing => $mount_command"
exec \
  s6-setuidgid abc $mount_command
